 
language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings

node_js:  
  - "12.18.3"

before_script:
  - psql -c 'create database  greetings;' -U postgres
  - psql -U postgres -d greetings -a -f greetings.sql

services:
  - postgresql
